# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

# on event workflows will be triggered
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

# what jobs will be run
jobs:
    test:
        runs-on: ubuntu-latest # this is the container

        # Execution steps
        steps:
            # Step 1: Checkout the code from the respository
            - name: Check out code
              uses: actions/checkout@v2
            
            # Step 2:
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                python-version: "3.8"
            
            # Step 3:
            - name: Install dependecies
              run: |
                python -m pip install --upgrade pip
                pip install install -r requirements.txt
            
            # Step 4:
            - name: Run the test
              run: pytest
